[BEAM-4294] [BEAM-4360] Join translation and ReduceByKey test suite where moved to org.apache.beam.* package.
seznam/beam pull request #1
Opened 2018-05-21 07:21 UTC by VaclavPlajt

This pull requests summaries together all the changes described in:
* https://github.com/mareksimunek/beam/pull/2 
* https://github.com/mareksimunek/beam/pull/3
Plus small imports fixes after rebase to https://github.com/seznam/beam/commit/eff3ffd5d224c6628606b355e3a5b6d8bc40150b. So please review them first to get understanding of this pull request.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [X] Write a pull request description that is detailed enough to understand:
   - [X] What the pull request does
   - [X] Why it does it
   - [X] How it does it
   - [ ] Why this approach
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Run `./gradlew build` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

2018-05-21 10:40 UTC, dmvk requested changes
Looks good overall! Good job 👍 Please introduce a check whether RBK can be translated using current translator and we're good to go ;)

2018-05-21 10:40 UTC, dmvk commented on sdks/java/extensions/euphoria/euphoria-beam/src/test/java/org/apache/beam/sdk/extensions/euphoria/beam/JoinTest.java
> +    BinaryFunctor<Optional<Pair<Integer, String>>, Pair<Integer, Integer>, Pair<String, Integer>>
it's usually more readable to apply lambda directly or to create named static function and use it by reference

2018-05-21 10:40 UTC, dmvk commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/ReduceByKeyTranslator.java
> +    if (operator.getValueComparator() != null) { //TODO Could we even do values sorting ?
`Preconditions.checkState`

2018-05-21 10:40 UTC, dmvk commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/FlowTranslator.java
>      translators.put(ReduceByKey.class, new ReduceByKeyTranslator());
we need to add predicate for reduce by key translator as it can not handle some cases (eg. if it contains value comparator). Predicates also allow us to have more implementations for a single operator (to handle different cases)

2018-05-21 10:40 UTC, dmvk commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/FlowTranslator.java
>      translators.put(ReduceByKey.class, new ReduceByKeyTranslator());
I reckon it would be worth adding a `boolean canTranslate` to the `OperatorTranslator` interface.

2018-05-21 10:40 UTC, dmvk commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/JoinTranslator.java
> +    PCollection<KV<K, ValueT>> leftKvInput =
-> `kvInput`

2018-05-21 10:40 UTC, dmvk commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/common/InputToKvDoFn.java
> +    this.keyExtractor = leftKeyExtractor;
`leftKeyExtractor` -> `keyExtractor`

2018-05-21 11:23 UTC, VaclavPlajt commented on sdks/java/extensions/euphoria/euphoria-beam/src/test/java/org/apache/beam/sdk/extensions/euphoria/beam/JoinTest.java
> +    BinaryFunctor<Optional<Pair<Integer, String>>, Pair<Integer, Integer>, Pair<String, Integer>>
I agree. Code was changed so the lambda is is used directly.
This case is more specific since the API requires type parameters of `BinaryFunctor` to be stated explicitly, otherwise parameter to the `output()` method has inferred arguments type which cannot be assigned from `ListDataSink<Pair<Integer, Pair<String, Integer>>> ` (`output` variable).

2018-05-21 11:24 UTC, VaclavPlajt commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/ReduceByKeyTranslator.java
> +    if (operator.getValueComparator() != null) { //TODO Could we even do values sorting ?
Fixed.

2018-05-21 13:03 UTC, VaclavPlajt commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/FlowTranslator.java
>      translators.put(ReduceByKey.class, new ReduceByKeyTranslator());
New method `boolean canTranslate(operator)` added to `OperatorTranslator`. Now we have ability to explicitly state when given translator cannot translate given `Operator`. We can also add more specialized translators when needed.

2018-05-21 13:03 UTC, VaclavPlajt commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/JoinTranslator.java
> +    PCollection<KV<K, ValueT>> leftKvInput =
Fixed.

2018-05-21 13:03 UTC, VaclavPlajt commented on sdks/java/extensions/euphoria/euphoria-beam/src/main/java/org/apache/beam/sdk/extensions/euphoria/beam/common/InputToKvDoFn.java
> +    this.keyExtractor = leftKeyExtractor;
Fixed.

2018-05-22 06:07 UTC, dmvk approved these changes

2018-05-22 06:08 UTC, dmvk commented
LGTM 👍 Good job. Can we send a pull request directly to `apache/beam` repository and than pull the changes to our repo?

2018-05-22 07:09 UTC, merged